### PR TITLE
Add Planned Enhancement: Unknown prefix

### LINKED ISSUE #199: [PE-D][Tester E] Unknown Error when inputting unknown parameter
When using the createMember function, if a non understood parameter such as q is used, the result display does not show what the possible error is and will still retain whatever is currently within the result display box.

From the image above, the result display was from when i was testing the phone number input and after attempting to use an unknown parameter q, the result display did not change.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: prawnzyy/ped#1

### PR DESCRIPTION
**Pull request by SelwynAng**
Closes #199 

- Added Planned Enhancement: Specific error message for unknown prefix

### CODE REVIEW

**Review by wr1159 — APPROVED** [review]
LGTM, do we need to mention something related to address will not be able to take any prefix in the string afterwards? Like anything with {alphabet}/

**Comment by andrechuakj** [comment]
> LGTM, do we need to mention something related to address will not be able to take any prefix in the string afterwards? Like anything with {alphabet}/

I don't think address will not be able to take any prefix in the string afterwards, just the prefixes that are used in that particular command. E.g. `createMember n/MEMBER_NAME g/GENDER [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...`, so `address` should not have any `n/`, `g/`, `p/`, `e/`, `a/` or `t/` prefixes. 

I have included this constraint in PR #254, do you think that will be sufficient?

**Comment by wr1159** [comment]
I think the selected prefix exclusion part will suffice for our UG.

After the planned enhancement of raising unknwon prefix error, wouldn't we not allow any unknown prefix in address since it will be  caught by the new parser?

**Comment by andrechuakj** [comment]
Yup unknown prefix will be caught by parser if we implemented the planned enhancement. In this case, we should only keep either the exclusion of known prefix in address or the exclusion of all unknown prefixes.

In my opinion, I think we should keep the exclusion of known prefix in address so that users will still have some flexibility with their addresses, as compared to no prefixes in the address at all.

**Comment by wr1159** [comment]
> In my opinion, I think we should keep the exclusion of known prefix in address so that users will still have some flexibility with their addresses, as compared to no prefixes in the address at all.

How will we differentiate whether this is an unknown prefix to be caught by the parser or a valid part of the address?

**Review by andrechuakj — APPROVED** [review]
LGTM

**Pull request merged**
