### PR TITLE
Planned enhancement: Specific error message for negative index

### LINKED ISSUE #207: [PE-D][Tester B] Display wrong type of error message for invalid index
According to the UG, MEMBER_INDEX must be a positive integer.

When there are 6 members:
If I enter the command `editMember 7 g/Female`
The error message is `The member index provided is invalid`

It is good that you inform user that the index is invalid, as user can clearly understand what's wrong with their command.

However, when enter negative number as MEMBER_INDEX, it will show another type of error.

For example, when enter command `editMember -7 g/Female`
Error message:
```
Invalid command format! 
editMember: Edits the details of the member identified by the index number used in the displayed member list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [g/GENDER] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]...
Example: editMember 1 p/91234567 e/johndoe@example.com
```

I guess that it will be better to show invalid index for negative index, which is already done by you in handling big index (Good jobs!).

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: KumChaiYin/ped#2

### PR DESCRIPTION
**Pull request by SelwynAng**
Closes #207 

- Added Planned Enhancement: Show a more specific error message for negative index in `editMember` and `editEvent`

### CODE REVIEW

**Comment by wr1159** [comment]
is this only for editEvent and editMember? Does viewMember and viewEvent not have this bug?

**Comment by SelwynAng** [comment]
> is this only for editEvent and editMember? Does viewMember and viewEvent not have this bug?

I believe that `viewMember`, `viewEvent`, `deleteMember` and `deleteEvent` have this bug too. Should I update this PR to include these 4 commands too?

**Comment by wr1159** [comment]
Yep I think so

**Review by wr1159 — APPROVED** [review]
LGTM

**Pull request merged**
