### PR TITLE
User Guide: Add images

### LINKED ISSUE #233: [PE-D][Tester B] Not enough visuals in UG
I'm impressed by your effort on designing your UI to make it visual attractive, you even have the options of dark and light mode.

I notice that there is a screenshot of your application in your UG. Maybe you would like to have more visual in your UG.

- Can insert screenshot/diagram to make it more attractive to users

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: KumChaiYin/ped#7

### PR DESCRIPTION
**Pull request by andrechuakj**
Closes #233

What have you done in this PR?
* Add screenshots for `list` command
* Add screenshots for `viewMember` command
* Add screenshots for `viewEvent` command

### CODE REVIEW

**Review by SelwynAng — COMMENTED** [review]
LGTM! However, I am thinking if there is a way for us to incorporate the commands that the user input in the command box as it is not shown in the screenshots as of now.

**Comment by andrechuakj** [comment]
I was thinking about that too, but because of how the command disappears after entering the command, leaving the command in the command box may appear to go against the expected behavior. 

Does anyone have any suggestions? @dylkaw @ph-nathan @wr1159

**Comment by wr1159** [comment]
as in do you mean to show the command the users typed?

**Comment by SelwynAng** [comment]
> as in do you mean to show the command the users typed?

Yes, I think we should show the command that the users typed in to make it clearer, but I don't think it is necessary, it's just nice to have.

**Comment by wr1159** [comment]
I think we can add the description to the image something to the meaning of : expected view after running (blank) command

**Comment by SelwynAng** [comment]
Agree with @wr1159.

**Pull request merged**
